### ISSUE TITLE
Rewrite Recovery bundle

### ISSUE THREAD

**Issue by shyim** [shopware/proposal#11]
**Priority**: high
**Effort**: high
**Forward Compatible**: Yes/No

### Description

The current recovery bundle is a Slim Framework application, which is custom-built and does not use the same logic to install / update Shopware as the built-in commands. The application is also outdated with the framework version and needs an entire rewrite for the next update. 

### Benefits

- Future proof installer
- PHP 8.1 compatibility
- Unified installing/updating experience between all methods

### Breaks strategy

The recovery bundle is internal

**Comment by JoshuaBehrens** [comment]
In the past it broke on making API calls to a self-signed/untrusted HTTPS cert which just stops the process :(
