### ISSUE TITLE
Manage composer packages of plugins using Composer

### ISSUE THREAD

**Issue by shyim** [shopware/proposal#14]
**Effort**: high

### Description

Plugins can currently define a list of composer dependencies in their `composer.json`. As Shopware currently checks only for the existence of the dependencies, extensions have to bring the own vendor folder.

The plugin vendor folder must contain only the dependencies which are not included in the Core to forbid class resolution / signature issues or scope the entire vendor folder

As the auto-updater works by file patching, we need to rewrite the entire updater application to update using Composer to consider the plugin dependencies.

### Benefits

The dependencies in plugins will be much easier than:

- Plugins don't need to ship a `vendor` folder with the zip
- No dependency collision between multiple `vendor` directories

### Breaks strategy

- Plugins needs to be adjusted to not load shipped vendor folder

**Comment by martinweinmayr** [comment]
i can confirm that this is not that funny to handle

**Comment by kleinmann** [comment]
This may have some effects on performance/timeouts during plugin installation, especially from the administration, if dependencies need to be fetched and resolved first. May also conflict with some firewall configurations (yeah, I don't want those around either 😄), but that can be handled with documentation.

**Comment by leptoquark1** [comment]
This seems to be related to `FEATURE_NEXT_1797`:

https://github.com/shopware/platform/blob/65cea618bfef1ba15a4ec6c021e7d9f1f70d44fc/src/Core/Framework/Plugin/PluginLifecycleService.php#L128-L140

What exactly is missing here?

**Comment by mitelg** [comment]
@leptoquark1 nothing 😁 it is already usable.
BUT cases like for example updating Shopware from admin are not working. for this https://github.com/shopware/proposal/issues/11 is needed
