### ISSUE TITLE
Queue System v2

### ISSUE THREAD

**Issue by OliverSkroblin** [shopware/proposal#18]
**Effort**: middle

### Description
The current queue system in `shopware\core` was implemented with the beta version of symfony messenger. This has changed a lot in the meantime. Furthermore, the queue system was rebuilt to certain requirements of us, but with the standard of Symfony Messenger, today there would no longer be necessary.

Therefore we would like to go back to the Symfony basics with the next major version.

We would also remove the `enqueue` table and move away from throwing serialized objects into the message queue.

### Benefits
* Allow to simply change the queue storage/system
* Allow multiple channels to optimize queue worker resources
* Get back to symfony defaults

### Break strategy
We will support both systems in the 6.4 line. This means that we are already converting our internal messages to the new system, but we will still be able to dispatch and manage messages via the old system. This ensures backward compatibility for third-party developers, but the new technology can already be used.

**Comment by JoshuaBehrens** [comment]
PHP serialization is also an issue regarding compatibility BC breaks for internal variables. Usage of serialize makes private variables "public API" and thus break everything that has been serialized/on the queue once.
