### ISSUE TITLE
Bootstrap 5 Support

### ISSUE THREAD

**Issue by bjoern-flagbit** [shopware/proposal#24]
**Effort**: high

### Description: 
It should be possible to use the default storefront with bootstrap version 5.

### Benefits
- Performance, flexibility
- Individual or compiled JavaScript
- Vanilla JavaScript instead of jQuery
- Improved Grid System
- IE 10 and 11 support removed
- RTL Support

### Break strategy
It could be possible to have a second core template that supports the new bootstrap 5 version.
You will need two different build processes. To not break to working bootstrap 4 process.
It musst be possible to build the plugins without jquery, bootstrap and other required vendors by bootstrap 4.

**Comment by shyim** [comment]
Is already on the way, is expected to be merged next week

**Comment by shyim** [comment]
I will close this as it's already publicly available https://www.shopware.com/en/news/developer-news-bootstrap-5-coming-soon/
