### ISSUE TITLE
Tailwind CSS Theme

### ISSUE THREAD

**Issue by luismarquesfreire** [shopware/proposal#26]
**Effort**: middle

### Description: 
Tailwind CSS theme allows for a completely different approach using utility css without any css code which will result in a much easier theming. It integrates greatly with Twig blocks as it allows for component separation which is very important using Tailwind CSS. Moreover, we also have TailwindCSS Ui which provides basically all building blocks for an eCommerce store with really great looks. See [https://tailwindcss.com/](https://tailwindcss.com/) and [https://tailwindui.com/#product-ecommerce](https://tailwindui.com/#product-ecommerce). There is already a project on Github but I don't really know if it is something from the Shopware team [https://github.com/flagbit/shopware6-tailwind-theme](https://github.com/flagbit/shopware6-tailwind-theme).

### Benefits
Less css code, less mess. Much greater developer experience theming and a more modern approach in frontend development.

### Break strategy
No need for breaking changes, it would be a choice for frontend developers to use the classic approach or the utility css approach using Tailwind CSS.

**Comment by JoshuaBehrens** [comment]
Different frameworks for themes is IMHO handled best with a completely different base theme. But adding more base themes reduces compatibility with store plugins. They need to have support for this. When there is no support it won't be used eventually.

**Comment by OliverSkroblin** [comment]
That's correct @JoshuaBehrens. We (and plugin developers) has much effort by keeping just the two themes of us compatible. New themes which are based on other frameworks are a perfect case for community or store driven themes. 👍

**Comment by Vhulcan** [comment]
I'm not a fan of the currently used Bootstrap framework, but Tailwind isn't a solution and would cause more issues than it solves.

Some concerns I have that come up right away when thinking about this:

- If you had a custom theme based on the Tailwind base theme, and you wanted to change how something looks, your whole custom theme is probably just going to be a big collection of extended Twig blocks and pages. This breaks compatibility with future Shopware updates and can cause a lot of compatibility issues with store plugins that also extend those blocks.
- Is the purge of unused CSS classes/JIT going to fully work with all plugins and apps in all different use cases?
- What about the JavaScript plugin system of Shopware? Seems like a lot will have to be rewritten as it uses CSS classes. Making the JS plugins work for both Bootstrap and Tailwind seems like to much of a pain.

**Comment by bjoern-flagbit** [comment]
@Vhulcan in my mind there is already the solution to get the PluginSystem working without the overhead from vendor. And this will be pushed to the flagbit tailwindcss theme. But I can also confirm that building a theme next to the core theme, needs more then just one or two persons. What I can not confirm is that debugging twig errors or checking what changed in core template to get it into you custom theme is not really much effort.

**Comment by ROBJkE** [comment]
> **it allows for component separation**  

Important point. The current state of shopwares default theme is horrible when it comes to component separation. In first place the twig templating of the default theme needs to be component based. Regardless of using tailwind, any other utility CSS framework or even Bootstrap.

**Comment by shyim** [comment]
Hey,

We support already Tailwind in [Shopware Frontends](https://www.shopware.com/en/news/frontends-yet-another-storefront/). We don't plan to bring our existing PHP Storefront to Tailwind as we recently just updated to Bootstrap 5.
