### ISSUE TITLE
Add webp support for images

### ISSUE THREAD

**Issue by schwertel-korodrogerie** [shopware/proposal#27]
**Effort**: middle

### Description: 
It should be possible to work with webp images in the shop.

### Benefits:
- smaller file sizes -> less loading time of storefront bc of less data

**Comment by mitelg** [comment]
this is about things, that need a breaking change. I guess adding webp support does not need a break :thinking:

**Comment by OliverSkroblin** [comment]
As @mitelg already mentioned, this is more of a feature request. Please post a jira-issue for it. The proposal are purely for refactorings and break strategies.

**Comment by shyim** [comment]
It's implemented in 6.4.8.0.  See https://github.com/shopware/platform/commit/d5de0d8dfd13b95aac8af3125ed72e249d5929b3
