### ISSUE TITLE
Reduce sales channel context data

### ISSUE THREAD

**Issue by shyim** [shopware/proposal#3]
**Effort**: high

### Description

The `SalesChannelContext` data object contains currently too many unused fields. The creation of the context takes very long as we need to fetch all that data. With this proposal, we reduce the fields to only a very small limited set. Should be implemented with #15 

### Benefits
- improve stack performance
- improve rule system performance 
- simplify "store" dependencies
- reduce impact to generate context permutations

### Breaks
- We deprecate unwanted fields from the `SalesChannelContext` in 6.4 and announce it to extension developers
- We remove with 6.5 all deprecated fields

**Comment by kleinmann** [comment]
Do you already have a list of fields that would be removed?

**Comment by creinelt** [comment]
Maybe you should start a poll to find out which fields are really not used very often or not at all.
Otherwise that could may lead to a lot of problems in store plugins or even customer/shop individual plugins.
