### ISSUE TITLE
bin/console dal:refresh:index --only instead of --skip 

### ISSUE THREAD

**Issue by r4pt0s** [shopware/proposal#30]
**Effort**: low/middle

### Description: 
Currently the only way for refreshing just one index is by using the --skip flag and adding all indexers except of the one which you actually want to run. 
This is quite inconvenient because the list of indexers which the user might have to skip is longer than a list which the user might actually want to run. 

### Benefits
- shorter list of indexers for the command
- more flexibility for the user to decide which indexers should run
- better to understand for the user
- flow would be more logical 

### Break strategy
There is actually nothing which would break except of already configured cronjobs on the user side of infrastructure.

**Comment by rattananen** [comment]
We can add parameters for specific index.

do all
```
bin/console dal:refresh:index
```

do some 
```
bin/console dal:refresh:index product category
```

exclude
```
bin/console dal:refresh:index --skip=product
```

no break change

idea from mysqldump

**Comment by keulinho** [comment]
This feature is already implemented: https://github.com/shopware/platform/pull/2690
