### ISSUE TITLE
Enable partial entity fetching

### ISSUE THREAD

**Issue by mschop** [shopware/proposal#36]
**Effort**: middle

### Description: 

Currently all fields of an entity get loaded, when using the DAL. This is understandable, since the DAL always returns an entity class.

The problem here is, that this is really bad for performance.

E.g. in the case of the API, there is the `includes` field to restrict the fields that get fetched. But that field is not even used when fetching data from the database. All fields of an entity are loaded and then the not needed data is thrown away.

My suggestion is, to add an additional method to the repositories, that enable partial entity fetching:

```
$criteria = new Criteria([...]);
$fields = [
  'productNumber',
  'active',
  'stock',
];
$result = $productRepository->searchPartial($criteria, $fields);
```

`$result` could then be something of the following:

- an instance of stdClass
- an array
- a dynamic sub class of the entity class (I know sound ugly. Unsure about this)

The REST api could then use the `includes` field with the `searchPartial` method which would improve the performance of the API as well.

### Benefits

Performance :exclamation: 

### Break strategy

The only breaking change would be here, that some event listener, which react to entity loading would not be triggered. (E.g. if the API uses `searchPartial` when `includes` is given.

This means, that some code may need to be extended / fixed to work with the new method.

**Comment by OliverSkroblin** [comment]
Hey @mschop, thanks for the proposal. We already implemented this feature: [see here](https://github.com/shopware/platform/commit/50c45e65b5b8d0042478bacc4189ded877297c97) 

At the moment it is marked as internal, that we can test it and see if it brings the hoped performance improvements. After some tests we will remove the `@internal` flag and add documentation for it.
