### ISSUE TITLE
Dependency Updates

### ISSUE THREAD

**Issue by shyim** [shopware/proposal#6]
**Effort**: high

### Description

We want to update all of our dependencies to the next stable major version like:

- Symfony to 6.1
- Doctrine DBAL 3
- Flysystem 3
- ...

### Breaks strategy

Document dependencies

**Comment by JoshuaBehrens** [comment]
Please add a guide how to build a plugin that can work in two major versions so you can make an upgrade without depending on a competent agency :) This can break a shop so easy

**Comment by rvzug** [comment]
Yes, update to Doctrine DBAL v3 could fix this issue https://issues.shopware.com/issues/NEXT-18628
