### ISSUE TITLE
Remove AWS SDK from Core

### ISSUE THREAD

**Issue by shyim** [shopware/proposal#7]
**Priority**: low

### Description

The AWS SDK Library is a huge library, and we don't use it in the core. With this proposal, we want to remove it

### Benefits

- Our package size will be reduced by ~40mb

**Comment by JoshuaBehrens** [comment]
Will you leave it as a suggest? What was the initial use case?

**Comment by shyim** [comment]
S3 bucket communication. Async AWS is there more flexible and is much smaller https://async-aws.com/

**Comment by JuicyLung91** [comment]
How will the implementation described [here](https://developer.shopware.com/docs/guides/hosting/infrastructure/filesystem#amazon-s3) change?

**Comment by shyim** [comment]
@JuicyLung91 That will not change as fly system doesn't use in the newest version aws sdk anymore

**Comment by JoshuaBehrens** [comment]
Is it done? @shyim which commit?

**Comment by shyim** [comment]
https://github.com/shopware/platform/commit/b9aaee23f7fb7a731b66bc92fbd4faeca4cbae99#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L60
